name: security_scan

on: [push]

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: "bandit"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r server
